spring:
  datasource:
    url: ${HH_DB_URL} # Environment variables to not hardcode values
    username: ${HH_DB_USERNAME}
    password: ${HH_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # Specifies how Hibernate should interact with existing tables
      show-sql: true


#spring:
#  profiles:
#    active:
#      - "@profileActive"