spring:
  datasource:
    url: ${HH_DB_URL} # Environment variables to not hardcode values
    username: ${HH_DB_USERNAME}
    password: ${HH_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Specifies how Hibernate should interact with existing tables
